### ISSUE TITLE
PolarTracker: Refactoring / Cleaning

### ISSUE THREAD

**Issue by casaout** [sealuzh/PersonalAnalytics#129]
- [x] line-chart: smoothed (wish from @tomFr) @manulita 
- [x] chooser => create event (instead of listener)
- [x] check if some more catches are needed

**Comment by s-mueller** [comment]
I would move 

chooser => create event (instead of listener)

to the next milestone to make sure we do not introduce any new bugs.

**Comment by s-mueller** [comment]
Lines are now smoothed (https://github.com/sealuzh/PersonalAnalytics/commit/4553fb9fbb0f06feba641f01160036eccee53c9b) @tomFr @manulita

**Comment by s-mueller** [comment]
Fixed last remaining issue in dev branch

**Comment by s-mueller** [comment]
Applied change also to GoalSetting branch
