### ISSUE TITLE
TaskDetection: Tool Set-Up

### ISSUE THREAD

**Issue by casaout** [sealuzh/PersonalAnalytics#148]
- [x] TaskDetectionTracker (Sebi)
- [x] TaskDetectionTrackerTest (Sebi)
    - [x] Katja CSV-file for demo-data => read and parse to model: TaskDetectionInput 
- [x] disable retrospection & unused trackers on branch (Andre)
- [x] model TaskDetectionInput (tsStart, tsEnd, process, List: windowtitle, userinput (??)
- [x] Model TaskDetection
    - [x] sessionId, tsStart, tsEnd, timeOfSwitch, taskTypeProposed, taskTypeValidated, taskDetectionCase (correct, wrong, missing, not_validated), comment
    - [x] timeline-infos: list: TaskDetectionInput

**Comment by s-mueller** [comment]
Model: https://github.com/sealuzh/PersonalAnalytics/commit/c2ac567e3cdaffe311d2bd0435a47bb15ff62114

**Comment by s-mueller** [comment]
Test data: https://github.com/sealuzh/PersonalAnalytics/commit/e301679475ef9a926a65fc6763338f0c9b92ddb4
