### ISSUE TITLE
TaskDetection-Helper

### ISSUE THREAD

**Issue by casaout** [sealuzh/PersonalAnalytics#149]
in TaskDetectionTracker and test with TaskDetectionTrackerTest

- [ ] create helper (use models as planned to create in https://github.com/sealuzh/PersonalAnalytics/issues/148) (Katja)
- [ ] use TaskDetectionTrackerHelper for testing (+ to demo usage) (Katja)
- [ ] implement helper for task boundary detection (from existing project) (Katja)
- [ ] algorithm for task type detection (based on observations) (Katja)
- [ ] implement helper for task type detection (Katja)
- [ ] improve algorithms based on new observations (Katja + Andre)

**Comment by casaout** [comment]
@katjakevic Can you please update (i.e. tick) here what is completed or close the issue? Thanks!
