### ISSUE TITLE
TaskDetection Validator PopUp

### ISSUE THREAD

**Issue by casaout** [sealuzh/PersonalAnalytics#150]
- [x] get necessary data from DB (and fill model, see https://github.com/sealuzh/PersonalAnalytics/issues/148)
- [x] task tray tooltip: show when next pop-up is going to be shown (see UserEfficiencyTracker)
- [x] UI: pop-up
    -  [x] load when all data is ready only
    -  [x] topmost: enforced, no postponing
    -  [x] timer (once an hour)
    -  [x] reminder (after 10 mins)
    -  [x] pop-up can only be saved when validation is complete (disable save button)
    -  [x] pop-up "X" (either disable or ask user to finish validation first)
- [x] UI: Timeline (visualize processes on timeline: per hour; group together same processes!)
- [x] UI: Mark main task with star
- [ ] UI: Details on hover
    - [x] 1) window title(s) 
    - [ ] 2) filter out files/websites (there is a helper for that in Shared.dll > WindowTitleArtifactExtractor)
    - [x] 3) user-input-stats (e.g. consumed/produced OR num of clicks/kexstrokes, etc.)
- [x] UI: Validation of task detection 
    - [x] 1) boundary: button correct/wrong
    - [x] 2) boundary: create new
    - [x] 3) type: dropdown from list
- [x] field for free-form-feedback
- [x] database stuff to save responses (scheme below)
- [x] use task type & task boundary helper (see https://github.com/sealuzh/PersonalAnalytics/issues/149)
- [x] save the timestamp of the last validation in the database (similar to IDLE validator) to not do it again when restarting

**Comment by casaout** [comment]
Validation for each TaskDetection-type: 1) correct 2) wrong 3) missing 4) non-validated (default)

**Comment by casaout** [comment]
Task Detection DB Scheme
![image](https://cloud.githubusercontent.com/assets/5212692/23956225/6957d292-099c-11e7-94a6-2026bd5639c4.png)

**Comment by s-mueller** [comment]
Is there anything missing that I need to implement?
