### ISSUE TITLE
UserInputTracker: Optimize Stored Data

### ISSUE THREAD

**Issue by casaout** [sealuzh/PersonalAnalytics#40]
store one entry once a minute with an aggregated view of all user inputs (don't store x,y anymore):
- •total #: key_other
- •total #: key_nav
- •total #: key_del
- •total #: mouse_clicks
- •total distance: mouse movement
- •total distance: mouse scrolled

This will also greatly improve the performance!

**Comment by casaout** [comment]
- [ ] update tracker
- [ ] update visualization
- [ ] update FlowTracker-Algorithm
- [ ] check (any other dependencies?)

**Comment by casaout** [comment]
**Update (Dec, 05, 2016):** 
- The new UserInputTracker stores an aggregate of all userinputs once a minute into a new table 'user_input'. This includes a start- and end-timestamp, total number of keystrokes (+ separate entries for types), total number of clicks (+ separate entries for type), nouse scroll delta and mouse movement distance. The advantage of this change are (1) much less storage needed (good for long-term deployment), (2) performance gains (in retrospection & other queries accessing the data)
- New in the UserInputTracker are events, which clients can register for (for each UserInput-type). The FlowTracker-Algorithm uses these events to use the own implementation of the userinput-data for the timewindow (currently: 3 minutes). I've updated the FlowTracker-project accordingly, and we need to test it.

**Next steps:**
- Testing **UserInputTracker**: I've tested it on my devices and it runs smoothly and stable so far (and the retrospection is so much faster now!)
- Testing **FlowTracker**: I asked @manulita to do a code review of my changes and test them. Afterwards, we will ask @boyangwm and @davidcshepherd to carefully test the new UserInputTracker and FlowTracker in the ABB-setup, before we roll it out.


Even though this change requires quite a bit of testing, I think it is an important one for our long-term development/deployment. The longer users were using the FocusLight, the slower everything would get. For the retrospection (that we will work on integrating next), this change will be much appreciated for the users. Thanks everyone!

CC: @tomFr

**Comment by boyangwm** [comment]
Hi @casaout , thank you for the updates

> Testing FlowTracker: I asked @manulita to do a code review of my changes and test them. Afterwards, we will ask @boyangwm and @davidcshepherd to carefully test the new UserInputTracker and FlowTracker in the ABB-setup, before we roll it out.

Please let us know if it's ready for testing. 1) We can start to apply release version for the DLLs based our discussion. 2) I will let you know (e.g., stack trace for the thread that consumes the most CPU time ) if we encountered a further issue. 

> @tomFr @boyangwm @davidcshepherd @manulita: Can you think of any other place we used the UserInputTracker (dependencies) and would need to make changes?

The open issue https://github.com/abb-iss/focuslight/issues/318 seems related to WindowsActivityTracker.dll. That is, when I rollbacked  WindowsActivityTracker.dll to the latest version (before deleting) in FlowTracker repo, the issue is resolved. 

Again, the issue has been resolved by using a **non-Latest** version of WindowsActivityTracker.dll in retrospection-playground.  It may or may not related to UserInputTracker, but it's worth to compare WindowsActivityTracker in "the latest version (before deleting) in FlowTracker repo" vs. "the latest version in retrospection-playground"

Please refer to a summary of **freezing/high CPU consumption** issues in https://github.com/abb-iss/focuslight/issues/318#issuecomment-258186510

**Comment by casaout** [comment]
@boyangwm Jup, I'll let you know as soon as @manulita is done testing. I'll also send you some more details on the change and what you could look for when testing (or we probably better discuss it quickly over S4B).

I've started working on abb-iss/focuslight#318 and made a comment there.

THanks!

**Comment by casaout** [comment]
Hi @boyangwm 

As discussed yesterday, we are ready to test the most recent changes to our trackers. I created [the folder "dlls"](https://github.com/sealuzh/PersonalAnalytics/tree/dev-am/documentation/dlls) where I've uploaded the current dlls and version numbers. From now on, please use these dlls for updates. 

- [ ] To test the updated **UserInputTracker.dll** and necessary changes to **FocusLightTracker.dll** please refer to this comment with details: https://github.com/sealuzh/PersonalAnalytics/issues/40#issuecomment-264834548 I think testing this change is very crucial before deployment. If possible, please run it on several of your dev/tester-machines and see if the light-color (i.e. flow-state) is still correct.

Please let me know in case you have any questions :) Thanks for your tests!

- André

(Btw, as soon as we are ready, I will also add the Retrospection.dll and MsOfficeTracker.dll to this folder.)

**Comment by casaout** [comment]
@boyangwm Do you have some feedback on the (new) UserInputTracker (see above)? Thanks!

**Comment by boyangwm** [comment]
@casaout , I did not see any major problems (until now) when I use the new UserInputTracker. I assume the lagging problem is from WindowsActivityTracker . https://github.com/abb-iss/focuslight/issues/318

**Comment by casaout** [comment]
Great to hear, thanks for testing! Yes, the lags are related to the other open issue abb-iss/focuslight#318. Thanks for testing!
